
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran de la Torre
 */
public class Voluntario1 extends javax.swing.JFrame {

    public Voluntario1() {
        initComponents();
    }
    private DecimalFormat f = new DecimalFormat("0.00");

    public void conversor(String Moneda) {
        try {
            switch (Moneda) {
                case "euro": {
                    float cantidad = Float.parseFloat(euro.getText());
                    dolar.setText("" + f.format(cantidad * 1.23));
                    libra.setText("" + f.format(cantidad * 0.88));
                    break;
                }
                case "dolar": {
                    float cantidad = Float.parseFloat(dolar.getText());
                    euro.setText("" + f.format(cantidad * 0.81));
                    libra.setText("" + f.format(cantidad * 0.71));
                    break;
                }
                case "libra": {
                    float cantidad = Float.parseFloat(libra.getText());
                    euro.setText("" + f.format(cantidad * 1.13));
                    dolar.setText("" + f.format(cantidad * 1.39));
                    break;
                }
            }

        } catch (NumberFormatException n) {
            if ("".equals(euro.getText())) {
                libra.setText(null);
                dolar.setText(null);
            }
            if ("".equals(euro.getText())) {
                libra.setText(null);
                dolar.setText(null);
            }
            if ("".equals(euro.getText())) {
                libra.setText(null);
                dolar.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Solo se pueden introducir números", "Error campos", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
        }
    }

    public void limpiar() {
        euro.setText(null);
        dolar.setText(null);
        libra.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        licono = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        euro = new java.awt.TextField();
        libra = new java.awt.TextField();
        dolar = new java.awt.TextField();

        d.setIconImage(null);
        d.setIconImages(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("SOLO SE PERMTE INTRODUCIR NUMEROS");

        Salir.setText("Cerrar");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dLayout = new javax.swing.GroupLayout(d.getContentPane());
        d.getContentPane().setLayout(dLayout);
        dLayout.setHorizontalGroup(
            dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(licono, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGroup(dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dLayout.setVerticalGroup(
            dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dLayout.createSequentialGroup()
                .addGroup(dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(licono, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Euro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 27, 22, 14);

        jLabel2.setText("Libra");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(163, 27, 23, 14);

        jLabel3.setText("Dolar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(323, 27, 25, 14);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(136, 82, 65, 23);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(270, 82, 65, 23);

        euro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                euroKeyReleased(evt);
            }
        });
        getContentPane().add(euro);
        euro.setBounds(56, 27, 80, 20);

        libra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                libraKeyReleased(evt);
            }
        });
        getContentPane().add(libra);
        libra.setBounds(213, 27, 84, 20);

        dolar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dolarKeyReleased(evt);
            }
        });
        getContentPane().add(dolar);
        dolar.setBounds(386, 27, 83, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
        euro.requestFocus();
    }//GEN-LAST:event_limpiarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        d.setVisible(false);
        limpiar();
    }//GEN-LAST:event_SalirActionPerformed

    private void euroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euroKeyReleased
        conversor("euro");
    }//GEN-LAST:event_euroKeyReleased

    private void libraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_libraKeyReleased
        conversor("libra");
    }//GEN-LAST:event_libraKeyReleased

    private void dolarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dolarKeyReleased
        conversor("dolar");
    }//GEN-LAST:event_dolarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voluntario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voluntario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voluntario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voluntario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voluntario1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JDialog d;
    private java.awt.TextField dolar;
    private java.awt.TextField euro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.TextField libra;
    private javax.swing.JLabel licono;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
