
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran De La Torre
 */
public class AgendaInterfaz extends javax.swing.JFrame {

    ControladorDB agenda;
    AgendaDB contacto;

    /**
     * Creates new form AgendaInterfaz
     */
    public AgendaInterfaz() {
        initComponents();
        agenda = new ControladorDB();
        rellenarListaDesplegable();

    }

    public void rellenarListaDesplegable() {
        ResultSet res = agenda.obtenerRegistros("contacto");
        if (res != null) {
            combo.removeAll();
            try {
                while (res.next()) {
                    combo.addItem(res.getString("nombre"));
                }
            } catch (SQLException evt) {
                System.err.println("meh");
            }
        }
    }

    public void mostrarRegistro() {
        String nom = "" + combo.getSelectedItem();
        AgendaDB contacto = agenda.obtenerContacto(nom);
        if (contacto != null) {
            jnombre.setText(contacto.getNombre());
            jdireccion.setText(contacto.getDireccion());
            jedad.setText("" + contacto.getEdad());
            jnumeros.setText(contacto.getTelefono());
            jlocalidad.setText(contacto.getLocalidad());
            jemail.setText(contacto.getEmail());
        }
    }

    public void nuevo() {
        leerDatos();
        agenda.nuevoContacto(contacto);
        rellenarListaDesplegable();
        limpiarCampos();
    }

    public void leerDatos() {
        String nom = jnombre.getText();
        String dir = jdireccion.getText();
        int edad = Integer.parseInt(jedad.getText());
        String num = jnumeros.getText();
        String loc = jlocalidad.getText();
        String email = jemail.getText();
        try {
            edad = Integer.parseInt(jedad.getText());
        } catch (NumberFormatException evt) {
        }
        contacto = new AgendaDB(nom, dir, num, loc, email, edad);
    }

    public void limpiarCampos() {
        jnombre.setText(null);
        jdireccion.setText(null);
        jedad.setText(null);
        jnumeros.setText(null);
        jlocalidad.setText(null);
        jemail.setText(null);

        jnombre.setRequestFocusEnabled(true);

    }

    public void modificar() {
        leerDatos();
        agenda.modificarContacto(contacto);
        limpiarCampos();
    }

    public void borrar() {
        String nom = jnombre.getText();
        agenda.borrarContacto(nom);
        limpiarCampos();
        rellenarListaDesplegable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jdireccion = new javax.swing.JTextField();
        jedad = new javax.swing.JTextField();
        jnumeros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlocalidad = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        nuevo = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(545, 460));
        getContentPane().setLayout(null);

        jLabel1.setText("Seleccionar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 40, 80, 16);

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        getContentPane().add(combo);
        combo.setBounds(170, 40, 220, 22);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del contacto"));
        jPanel1.setLayout(null);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 30, 50, 16);

        jLabel3.setText("Direccion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 70, 60, 16);

        jLabel4.setText("Edad");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(48, 110, 30, 16);

        jLabel5.setText("Numeros");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 150, 60, 16);
        jPanel1.add(jnombre);
        jnombre.setBounds(120, 30, 240, 22);
        jPanel1.add(jdireccion);
        jdireccion.setBounds(120, 70, 240, 22);
        jPanel1.add(jedad);
        jedad.setBounds(120, 110, 240, 22);
        jPanel1.add(jnumeros);
        jnumeros.setBounds(120, 150, 240, 22);

        jLabel6.setText("Localidad");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 190, 60, 16);

        jLabel7.setText("Email");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 230, 40, 16);
        jPanel1.add(jlocalidad);
        jlocalidad.setBounds(120, 190, 240, 22);
        jPanel1.add(jemail);
        jemail.setBounds(120, 230, 240, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 80, 400, 270);

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo);
        nuevo.setBounds(50, 360, 67, 25);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar);
        modificar.setBounds(140, 360, 100, 25);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar);
        borrar.setBounds(270, 360, 69, 25);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(380, 360, 59, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        mostrarRegistro();
    }//GEN-LAST:event_comboItemStateChanged

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        modificar();
    }//GEN-LAST:event_modificarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        borrar();
    }//GEN-LAST:event_borrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jdireccion;
    private javax.swing.JTextField jedad;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jlocalidad;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jnumeros;
    private javax.swing.JButton modificar;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
