
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran De La Torre
 */
public class jframe extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2;

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
        modelo.addColumn("Columna 1");
        modelo.addColumn("Columna 2");
        modelo.addColumn("Columna 3");
        tabla.setModel(modelo);
    }

    public void nuevaColumna() {
        String var;
        var = textfield.getText();
        if (!"".equals(var)) {
            modelo.addColumn(var);
        } else {
            System.err.println("No se puede añadir una columna sin nombre");
        }
    }

    public void añadirFila() {
        int numColumnas = modelo.getColumnCount();
        Object[] ob = new Object[numColumnas];
        modelo.addRow(ob);
        tabla.setModel(modelo);
    }

    /*
     public void añadirFila() {
     modelo.addRow(new Object[]{""});
     }*/
    
    
    public void eliminarFila() {
        try {
            modelo.removeRow(tabla.getSelectedRow());
        } catch (ArrayIndexOutOfBoundsException evt) {
            System.err.println("Que intentas borar?!?!");
        }
    }

    public void limpiarFilas() {
        try {
            int filas = tabla.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception evt) {
            System.err.println("Que intentas borar!?!?");
        }
    }

    public void cambiarNombre() {
        modelo2 = new DefaultTableModel();
        int ncol = modelo.getColumnCount();

        for (int i = 1; i <= ncol; i++) {
            modelo2.addColumn("Columna " + i);
        }
        Object[] fila = new Object[ncol];
        modelo2.addRow(fila);
        for (int i = 0; i < ncol; i++) {
            modelo2.setValueAt(modelo.getColumnName(i), 0, i);
        }
        tabla2.setModel(modelo2);
    }

    public void cambiarIdentificadores() {
        dialogo.pack();
        Vector identif = new Vector();
        for (int i = 0; i < modelo2.getColumnCount(); i++) {
            identif.add(tabla2.getValueAt(0, i));
        }
        modelo.setColumnIdentifiers(identif);
    }

    public void borrarColumna() {
        try {
            modelo.setColumnCount(modelo.getColumnCount() - 1);
        } catch (ArrayIndexOutOfBoundsException evt) {
            System.err.println("No puedes borrar colunmas que NO existen!!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        siguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        añadirf = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        nueva = new javax.swing.JButton();
        textfield = new javax.swing.JTextField();
        cambian = new javax.swing.JButton();
        borrarc = new javax.swing.JButton();

        dialogo.setMinimumSize(new java.awt.Dimension(580, 270));
        dialogo.getContentPane().setLayout(null);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla2);

        dialogo.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 50, 452, 70);

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(siguiente);
        siguiente.setBounds(220, 170, 100, 23);

        jLabel1.setText("Pulsa enter para que se apliquen los cambios en la tabla antes de pulsar siguiente");
        dialogo.getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 130, 480, 14);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 475));
        getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 20, 452, 230);

        añadirf.setText("Añadir Fila");
        añadirf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirfActionPerformed(evt);
            }
        });
        getContentPane().add(añadirf);
        añadirf.setBounds(50, 260, 130, 23);

        eliminar.setText("Eliminar Fila");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar);
        eliminar.setBounds(200, 260, 140, 23);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(360, 260, 130, 23);

        nueva.setText("Nueva Columna");
        nueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaMouseClicked(evt);
            }
        });
        nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActionPerformed(evt);
            }
        });
        getContentPane().add(nueva);
        nueva.setBounds(50, 330, 130, 23);

        textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldActionPerformed(evt);
            }
        });
        textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldKeyReleased(evt);
            }
        });
        getContentPane().add(textfield);
        textfield.setBounds(190, 330, 260, 20);

        cambian.setText("Cambiar nombre columna");
        cambian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambianActionPerformed(evt);
            }
        });
        getContentPane().add(cambian);
        cambian.setBounds(50, 390, 200, 23);

        borrarc.setText("Borrar columna");
        borrarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarcActionPerformed(evt);
            }
        });
        getContentPane().add(borrarc);
        borrarc.setBounds(270, 390, 220, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldActionPerformed

    private void añadirfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirfActionPerformed
        añadirFila();
    }//GEN-LAST:event_añadirfActionPerformed

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed
        nuevaColumna();
    }//GEN-LAST:event_nuevaActionPerformed

    private void textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            nuevaColumna();
            textfield.setText("");
        }
    }//GEN-LAST:event_textfieldKeyReleased

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        eliminarFila();
    }//GEN-LAST:event_eliminarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiarFilas();
    }//GEN-LAST:event_limpiarActionPerformed

    private void borrarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarcActionPerformed
        borrarColumna();
    }//GEN-LAST:event_borrarcActionPerformed

    private void cambianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambianActionPerformed
        dialogo.setVisible(true);
        cambiarNombre();
    }//GEN-LAST:event_cambianActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        cambiarIdentificadores();
        dialogo.setVisible(false);
    }//GEN-LAST:event_siguienteActionPerformed

    private void nuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaMouseClicked
        textfield.setText("");
    }//GEN-LAST:event_nuevaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirf;
    private javax.swing.JButton borrarc;
    private javax.swing.JButton cambian;
    private javax.swing.JDialog dialogo;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton nueva;
    private javax.swing.JButton siguiente;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla2;
    private javax.swing.JTextField textfield;
    // End of variables declaration//GEN-END:variables
}
