
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran De La Torre
 */
public class GUI02 extends javax.swing.JFrame implements Runnable {

    Thread hilo;

    /**
     * Creates new form GUI02
     */
    public GUI02() {
        initComponents();
        hilo = null;
    }

    public void run() {
        try {
            darTamaño();
            darColor();
            parpadear();
        } catch (InterruptedException e) {
        }
    }

    public void nuevoHilo() {
        if (hilo == null) {
            hilo = new Thread(this);
            hilo.start();
        }
    }

    public void parpadear() throws InterruptedException {
        int flag = 1;
        texto.setText(jtext.getText());
        while (Thread.currentThread() == hilo) {
            switch (flag) {
                case 1:
                    texto.setVisible(false);
                    flag = 0;
                    break;
                case 0:
                    texto.setVisible(true);
                    flag = 1;
                    break;
            }
            Thread.sleep(1000);
        }
    }

    public void darTamaño() {
        Integer i = Integer.parseInt(combo.getSelectedItem().toString());
        texto.setFont(new Font("Serif", Font.PLAIN, i));
    }

    public void darColor() {
        texto.setForeground(new Color(Srojo.getValue(), Sverde.getValue(), Sazul.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Sverde = new javax.swing.JScrollBar();
        Srojo = new javax.swing.JScrollBar();
        Sazul = new javax.swing.JScrollBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aplicar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jtext = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        texto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(texto);
        texto.setBounds(50, 50, 530, 90);

        jLabel2.setText("Texto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 32, 16);

        jLabel3.setText("Tamaño");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 50, 16);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Color"));
        jPanel1.setLayout(null);

        Sverde.setMaximum(255);
        Sverde.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel1.add(Sverde);
        Sverde.setBounds(370, 90, 100, 20);

        Srojo.setMaximum(255);
        Srojo.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel1.add(Srojo);
        Srojo.setBounds(30, 90, 100, 20);

        Sazul.setMaximum(255);
        Sazul.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel1.add(Sazul);
        Sazul.setBounds(200, 90, 100, 20);

        jLabel4.setText("Verde");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 30, 34, 16);

        jLabel5.setText("Rojo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 30, 26, 16);

        jLabel6.setText("Azul");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 30, 24, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 310, 520, 170);

        aplicar.setText("Aplicar");
        aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarActionPerformed(evt);
            }
        });
        getContentPane().add(aplicar);
        aplicar.setBounds(140, 510, 79, 25);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(380, 510, 79, 25);
        getContentPane().add(jtext);
        jtext.setBounds(100, 170, 170, 22);

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "6", "8", "10", "12", "14", "18", "24", "36", "48" }));
        getContentPane().add(combo);
        combo.setBounds(100, 250, 70, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarActionPerformed
        nuevoHilo();
    }//GEN-LAST:event_aplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar Sazul;
    private javax.swing.JScrollBar Srojo;
    private javax.swing.JScrollBar Sverde;
    private javax.swing.JButton aplicar;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtext;
    private javax.swing.JButton salir;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
