
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran De La Torre
 */
public class GUI01 extends javax.swing.JFrame implements Runnable {

    Thread cuentaMas;
    Thread cuentaMenos;

    /**
     * Creates new form GUI01
     */
    public GUI01() {
        initComponents();
        cuentaMas = null;
        cuentaMenos = null;
    }

    public void run() {
        try {
            comenzar1();
            comenzar2();
        } catch (InterruptedException e) {
        }
    }

    public void nuevoHilo1() {
        if (cuentaMas == null) {
            cuentaMas = new Thread(this);
            cuentaMas.start();
        }
    }

    public void nuevoHilo2() {
        if (cuentaMenos == null) {
            cuentaMenos = new Thread(this);
            cuentaMenos.start();
        }
    }

    public void comenzar1() throws InterruptedException {
        int i = 0;
        while (i <= 100 && Thread.currentThread() == cuentaMas) {
            tf1.setText("" + i);
            Thread.sleep(1000);
            i++;
        }
    }

    public void comenzar2() throws InterruptedException {
        int i = 100;
        while (i >= 1 && Thread.currentThread() == cuentaMenos) {
            tf2.setText("" + i);
            Thread.sleep(1000);
            i--;
        }
    }

    public void parar1() {
        cuentaMas.suspend();
    }

    public void parar2() {
        cuentaMenos.suspend();
    }
    
    public void reanudar1(){
        cuentaMas.resume();
    }
    public void reanudar2(){
        cuentaMenos.resume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        parar1 = new javax.swing.JButton();
        reanudar1 = new javax.swing.JButton();
        comenzar1 = new javax.swing.JButton();
        parar2 = new javax.swing.JButton();
        reanudar2 = new javax.swing.JButton();
        comenzar2 = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setPreferredSize(new java.awt.Dimension(750, 260));
        getContentPane().setLayout(null);
        getContentPane().add(tf1);
        tf1.setBounds(239, 30, 90, 22);
        getContentPane().add(tf2);
        tf2.setBounds(360, 30, 90, 22);

        parar1.setText("Parar");
        parar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parar1ActionPerformed(evt);
            }
        });
        getContentPane().add(parar1);
        parar1.setBounds(50, 120, 63, 25);

        reanudar1.setText("Reanudar");
        reanudar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudar1ActionPerformed(evt);
            }
        });
        getContentPane().add(reanudar1);
        reanudar1.setBounds(139, 120, 90, 25);

        comenzar1.setText("Comenzar");
        comenzar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzar1ActionPerformed(evt);
            }
        });
        getContentPane().add(comenzar1);
        comenzar1.setBounds(250, 120, 90, 25);

        parar2.setText("Parar");
        parar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parar2ActionPerformed(evt);
            }
        });
        getContentPane().add(parar2);
        parar2.setBounds(370, 120, 63, 25);

        reanudar2.setText("Reanudar");
        reanudar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudar2ActionPerformed(evt);
            }
        });
        getContentPane().add(reanudar2);
        reanudar2.setBounds(460, 120, 87, 25);

        comenzar2.setText("Comenzar");
        comenzar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzar2ActionPerformed(evt);
            }
        });
        getContentPane().add(comenzar2);
        comenzar2.setBounds(560, 120, 91, 25);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(310, 70, 59, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reanudar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudar2ActionPerformed
        reanudar2();
    }//GEN-LAST:event_reanudar2ActionPerformed

    private void comenzar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzar1ActionPerformed
        nuevoHilo1();
    }//GEN-LAST:event_comenzar1ActionPerformed

    private void comenzar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzar2ActionPerformed
        nuevoHilo2();
    }//GEN-LAST:event_comenzar2ActionPerformed

    private void parar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parar1ActionPerformed
        parar1();
    }//GEN-LAST:event_parar1ActionPerformed

    private void parar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parar2ActionPerformed
        parar2();
    }//GEN-LAST:event_parar2ActionPerformed

    private void reanudar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudar1ActionPerformed
        reanudar1();
    }//GEN-LAST:event_reanudar1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comenzar1;
    private javax.swing.JButton comenzar2;
    private javax.swing.JButton parar1;
    private javax.swing.JButton parar2;
    private javax.swing.JButton reanudar1;
    private javax.swing.JButton reanudar2;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
