
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fran De La Torre
 */
public class GUI03 extends javax.swing.JFrame implements Runnable {

    Thread reloj;
    int hora = 0;
    int minutos = 0;
    int segundos = 0;

    /**
     * Creates new form GUI03
     */
    public GUI03() {
        initComponents();
        reloj = null;
        nuevoHilo();
    }

    public void run() {
        try {
            hora();
        } catch (InterruptedException e) {
        }
    }

    public void nuevoHilo() {
        if (reloj == null) {
            reloj = new Thread(this);
            reloj.start();
        } else {
            reloj = new Thread(this);
            reloj.start();
        }
    }

    public void hora() throws InterruptedException {

        pantalla.setText(hora + ":" + minutos + ":" + segundos);
        while (true && Thread.currentThread() == reloj) {
            if (hora != 24) {
                if (segundos <= 60) {
                    segundos++;
                    pantalla.setText(String.format("%02d", hora) + ":" + String.format("%02d", minutos) + ":" + String.format("%02d", segundos));
                }
                if (segundos == 60) {
                    segundos = 0;
                    minutos++;
                    pantalla.setText(String.format("%02d", hora) + ":" + String.format("%02d", minutos) + ":" + String.format("%02d", segundos));
                }
                if (minutos == 60) {
                    minutos = 0;
                    hora++;
                    pantalla.setText(String.format("%02d", hora) + ":" + String.format("%02d", minutos) + ":" + String.format("%02d", segundos));

                }
            }

            if (hora >= 24) {
                hora = 0;
                minutos = 0;
                segundos = 0;
            }
            Thread.sleep(1000);
        }
    }

    public void ponerEnHora() {
        hora = parseInt(Jhora.getText());
        minutos = parseInt(Jminutos.getText());
        segundos = parseInt(Jsegundos.getText());

    }

    public void parar() {
        reloj.suspend();
    }

    public void reanudar() {
        reloj.resume();
    }

    public void resetear() {
        nuevoHilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        Jhora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jminutos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Jsegundos = new javax.swing.JTextField();
        aplicar = new javax.swing.JButton();
        pantalla = new javax.swing.JTextField();
        resetear = new javax.swing.JButton();
        parar = new javax.swing.JButton();
        reanudar = new javax.swing.JButton();
        Phora = new javax.swing.JButton();

        dialogo.setMinimumSize(new java.awt.Dimension(670, 140));
        dialogo.getContentPane().setLayout(null);

        jLabel1.setText("Hora");
        dialogo.getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 27, 16);

        Jhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhoraActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(Jhora);
        Jhora.setBounds(100, 20, 90, 22);

        jLabel2.setText("Minutos");
        dialogo.getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 44, 16);
        dialogo.getContentPane().add(Jminutos);
        Jminutos.setBounds(290, 20, 90, 22);

        jLabel3.setText("Segundos");
        dialogo.getContentPane().add(jLabel3);
        jLabel3.setBounds(407, 20, 70, 16);
        dialogo.getContentPane().add(Jsegundos);
        Jsegundos.setBounds(490, 20, 80, 22);

        aplicar.setText("Aplicar");
        aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(aplicar);
        aplicar.setBounds(270, 60, 71, 25);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 210));
        getContentPane().setLayout(null);

        pantalla.setEditable(false);
        getContentPane().add(pantalla);
        pantalla.setBounds(170, 20, 110, 22);

        resetear.setText("Resetear");
        resetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetearActionPerformed(evt);
            }
        });
        getContentPane().add(resetear);
        resetear.setBounds(50, 80, 90, 25);

        parar.setText("Parar");
        parar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararActionPerformed(evt);
            }
        });
        getContentPane().add(parar);
        parar.setBounds(200, 80, 63, 25);

        reanudar.setText("Reanudar");
        reanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudarActionPerformed(evt);
            }
        });
        getContentPane().add(reanudar);
        reanudar.setBounds(330, 80, 90, 25);

        Phora.setText("Poner en Hora");
        Phora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoraActionPerformed(evt);
            }
        });
        getContentPane().add(Phora);
        Phora.setBounds(170, 130, 130, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhoraActionPerformed
        nuevoHilo();
    }//GEN-LAST:event_JhoraActionPerformed

    private void PhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoraActionPerformed
        dialogo.setVisible(true);
    }//GEN-LAST:event_PhoraActionPerformed

    private void resetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetearActionPerformed
        resetear();
    }//GEN-LAST:event_resetearActionPerformed

    private void pararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararActionPerformed
        parar();
    }//GEN-LAST:event_pararActionPerformed

    private void reanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudarActionPerformed
        reanudar();
    }//GEN-LAST:event_reanudarActionPerformed

    private void aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarActionPerformed
        dialogo.setVisible(false);
        ponerEnHora();
        nuevoHilo();
    }//GEN-LAST:event_aplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jhora;
    private javax.swing.JTextField Jminutos;
    private javax.swing.JTextField Jsegundos;
    private javax.swing.JButton Phora;
    private javax.swing.JButton aplicar;
    private javax.swing.JDialog dialogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pantalla;
    private javax.swing.JButton parar;
    private javax.swing.JButton reanudar;
    private javax.swing.JButton resetear;
    // End of variables declaration//GEN-END:variables
}
