/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fran De La Torre
 */
public class Quiniela extends java.awt.Frame {

    /**
     * Creates new form Quiniela
     */
    public Quiniela() {
        initComponents();
    }
 /**
 * Metodo para vaciar todos los datos de los componentes
 * No devuelve nada
 */
    public void vaciar(){
        list1.removeAll();
        list2.removeAll();
    
    }
/**
 * Abre una nueva ventana de dialogo para añadir partidos a la ventana
 * Cada vez que añades uno el focus se restablece en el textfield del dialogo 
 */    
    public void nuevo(){
        dialogo.setVisible(true);
        dialogo.pack();
        dialogo.setLocation(300, 200);
        tfdialogo.requestFocus();
    }
/**
 *Boton añadir, cada vez que lo pulsas lo que hay en el textfield lo adiciona a
 * la lista y restablece el valor a vacio para volver a escribir 
 */
    public void add(){
        list2.add(tfdialogo.getText());        
        tfdialogo.setText("");
        tfdialogo.requestFocus();
    }
 
/**
 * Cuando seleccionas en la lista algo para borrar lo elimina cuando pulsas en
 * el boton borrar, gestiona el error en caso de que no este seleccionado nada 
 */    

    public void borrar(){
        try{
            int i = list2.getSelectedIndex();
            list2.remove(i);
        }catch(Exception evt){
            System.err.println("Necesita seleccionar un partido para borrar. "
            + evt);
            
        }
    }
/**
 * Cuando pulsas el boton generar, genera con los partidos anteriormente introducidos
 * una quiniela aleatoria. Los valores son del 50% para el 1, 30% para la x y 
 * 20% para el 2 
 */
    public void generar(){
        int i;
        for(int j=0; j<list2.getItemCount(); j++){
            i = (int)(Math.random()*(10)+1);
            if(i<=5){
                list1.add(list2.getItem(j)+ " 1");
            }else if(i<=8){
                list1.add(list2.getItem(j)+" x");
            }else if(i<=10){
                list1.add(list2.getItem(j)+" 2");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo = new javax.swing.JDialog();
        labeldialogo = new javax.swing.JLabel();
        addboton = new javax.swing.JButton();
        tfdialogo = new javax.swing.JTextField();
        nuevo = new java.awt.Button();
        borrar = new java.awt.Button();
        vaciar = new java.awt.Button();
        generar = new java.awt.Button();
        label1 = new java.awt.Label();
        list1 = new java.awt.List();
        list2 = new java.awt.List();

        dialogo.setMinimumSize(new java.awt.Dimension(590, 110));
        dialogo.getContentPane().setLayout(null);

        labeldialogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labeldialogo.setText("PARTIDO");
        dialogo.getContentPane().add(labeldialogo);
        labeldialogo.setBounds(20, 10, 100, 50);

        addboton.setText("OK");
        addboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbotonActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(addboton);
        addboton.setBounds(510, 30, 60, 31);

        tfdialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdialogoActionPerformed(evt);
            }
        });
        dialogo.getContentPane().add(tfdialogo);
        tfdialogo.setBounds(130, 20, 350, 40);

        setMinimumSize(new java.awt.Dimension(585, 483));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        nuevo.setLabel("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        add(nuevo);
        nuevo.setBounds(240, 150, 54, 23);

        borrar.setLabel("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        add(borrar);
        borrar.setBounds(240, 200, 53, 23);

        vaciar.setLabel("Vaciar");
        vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarActionPerformed(evt);
            }
        });
        add(vaciar);
        vaciar.setBounds(240, 260, 53, 23);

        generar.setLabel("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        add(generar);
        generar.setBounds(230, 350, 70, 30);

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 51, 51));
        label1.setText("GENERADOR DE QUINIELAS");
        add(label1);
        label1.setBounds(30, 20, 560, 80);
        add(list1);
        list1.setBounds(340, 100, 190, 310);

        list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2ActionPerformed(evt);
            }
        });
        add(list2);
        list2.setBounds(20, 100, 190, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Salida de la aplicacion
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void list2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2ActionPerformed

    }//GEN-LAST:event_list2ActionPerformed
    /**
 *
 * llamada a la funcion cuando se pulsa el boton
 */
    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_nuevoActionPerformed
/**
 *
 * llamada a la funcion cuando se pulsa el boton
 */
    private void vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarActionPerformed
        vaciar();
    }//GEN-LAST:event_vaciarActionPerformed
/**
 *
 * llamada a la funcion cuando se pulsa el boton
 */
    private void addbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbotonActionPerformed
        add();
    }//GEN-LAST:event_addbotonActionPerformed
/**
 *
 * llamada a la funcion cuando se pulsa el boton
 */
    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        borrar();
    }//GEN-LAST:event_borrarActionPerformed
/**
 *
 * llamada a la funcion cuando se pulsa el boton
 */
    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        generar();
    }//GEN-LAST:event_generarActionPerformed
/**
 *
 * llamada a la funcion cuando se pulsa el boton
 */
    private void tfdialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdialogoActionPerformed
        add();
    }//GEN-LAST:event_tfdialogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiniela().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addboton;
    private java.awt.Button borrar;
    private javax.swing.JDialog dialogo;
    private java.awt.Button generar;
    private java.awt.Label label1;
    private javax.swing.JLabel labeldialogo;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.Button nuevo;
    private javax.swing.JTextField tfdialogo;
    private java.awt.Button vaciar;
    // End of variables declaration//GEN-END:variables
}
