/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fran De La Torre
 */
public class Ejercicio2 extends java.awt.Frame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        scroll = new java.awt.Scrollbar();
        reset = new java.awt.Button();
        mes = new java.awt.Choice();
        dia = new java.awt.Choice();

        setMinimumSize(new java.awt.Dimension(585, 384));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Día");
        add(label1);
        label1.setBounds(80, 60, 25, 23);

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setText("Mes");
        add(label2);
        label2.setBounds(330, 60, 30, 23);

        scroll.setBlockIncrement(1);
        scroll.setMaximum(374);
        scroll.setOrientation(java.awt.Scrollbar.HORIZONTAL);
        scroll.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                scrollAdjustmentValueChanged(evt);
            }
        });
        add(scroll);
        scroll.setBounds(160, 190, 240, 16);

        reset.setLabel("Resetear");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        add(reset);
        reset.setBounds(250, 250, 67, 24);
        add(mes);
        mes.setBounds(400, 60, 110, 20);
        mes.add("Enero");
        mes.add("Febrero");
        mes.add("Marzo");
        mes.add("Abril");
        mes.add("Mayo");
        mes.add("Junio");
        mes.add("Julio");
        mes.add("Agosto");
        mes.add("Septiembre");
        mes.add("Octubre");
        mes.add("Noviembre");
        mes.add("Diciembre");
        add(dia);
        dia.setBounds(140, 60, 60, 20);
        dia.add("1");
        dia.add("2");
        dia.add("3");
        dia.add("4");
        dia.add("5");
        dia.add("6");
        dia.add("7");
        dia.add("8");
        dia.add("9");
        dia.add("10");
        dia.add("11");
        dia.add("12");
        dia.add("13");
        dia.add("14");
        dia.add("15");
        dia.add("16");
        dia.add("17");
        dia.add("18");
        dia.add("19");
        dia.add("20");
        dia.add("21");
        dia.add("22");
        dia.add("23");
        dia.add("24");
        dia.add("25");
        dia.add("26");
        dia.add("27");
        dia.add("28");
        dia.add("29");
        dia.add("30");
        dia.add("31");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void scrollAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_scrollAdjustmentValueChanged
        // TODO add your handling code here:
        int valorScroll = scroll.getValue();
        
        if (valorScroll > 1 && valorScroll <=31){
            dia.select(valorScroll);
            mes.select(0);
        }
        
        if (valorScroll > 31 && valorScroll <=59){
            dia.select(valorScroll-31);            
            mes.select(1);
            
        } 
        
        if (valorScroll > 59 && valorScroll <=90){
            dia.select(valorScroll-59);
            mes.select(2);
        } 
        
        if (valorScroll > 90 && valorScroll <=120){
            dia.select(valorScroll-90);
            mes.select(3);
        } 
        
        if (valorScroll > 120 && valorScroll <=151){
            dia.select(valorScroll-120);
            mes.select(4);
        } 
        
        if (valorScroll > 151 && valorScroll <=181){
            dia.select(valorScroll-151);
            mes.select(5);
        } 
        
        if (valorScroll > 181 && valorScroll <=212){
            dia.select(valorScroll-181);
            mes.select(6);
        } 
        
        if (valorScroll > 212 && valorScroll <=243){
            dia.select(valorScroll-212);
            mes.select(7);
        } 
        
        if (valorScroll > 243 && valorScroll <=273){
            dia.select(valorScroll-243);
            mes.select(8);
        } 
        
        if (valorScroll > 273 && valorScroll <=304){
            dia.select(valorScroll-273);
            mes.select(9);
        } 
        
        if (valorScroll > 304 && valorScroll <=343){
            dia.select(valorScroll-304);
            mes.select(10);
        } 
        
        if (valorScroll > 334 && valorScroll <=365){
            dia.select(valorScroll-334);
            mes.select(11);
        } 
        
    }//GEN-LAST:event_scrollAdjustmentValueChanged

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        dia.select(0);
        mes.select(0);
        scroll.setValue(0);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice dia;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Choice mes;
    private java.awt.Button reset;
    private java.awt.Scrollbar scroll;
    // End of variables declaration//GEN-END:variables
}
