
import java.util.ArrayList;

/**
 *
 * @author Fran De La Torre
 */
public class GUI02 extends javax.swing.JFrame {
    
    ArrayList<Integer> lista1 = new ArrayList<Integer>();
    ArrayList<Integer> lista2 = new ArrayList<Integer>();

    /**
     * Creates new form GUI02
     */
    public GUI02() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public void nuevo() {
        simulaciones.setText("");
        casos.setText("");
        probabilidad.setText("");
        simulaciones.requestFocus();
    }
    
    public void generar() {
        int aux = Integer.parseInt(simulaciones.getText());
        int aux2 = 0;
        
        if (simular.isSelected() == true) {
            Bombo bombo = new Bombo(49);
            for (int i = 0; i < 6; i++) {
                lista1.add(i, bombo.sacaBola() + 1);
            }
            lista1.sort(null);
            
            for (int k = 0; k < lista1.size(); k++) {
                for (int i = 0; i < tabla2.getColumnCount(); i++) {
                    for (int j = 0; j < tabla2.getRowCount(); j++) {
                        tabla1.setValueAt(lista1.get(k), j, i);
                        lista1.remove(k);
                    }
                }
            }
        }
        if (generar.isSelected() == true) {
            for (int x = 0; x < aux; x++) {
                Bombo bombo = new Bombo(49);
                for (int i = 0; i < 6; i++) {
                    lista2.add(i, bombo.sacaBola() + 1);
                }
                lista2.sort(null);
                
                for (int k = 0; k < lista2.size(); k++) {
                    for (int i = 0; i < tabla2.getColumnCount(); i++) {
                        for (int j = 0; j < tabla2.getRowCount(); j++) {
                            tabla1.setValueAt(lista2.get(k), j, i);
                            if (lista1 == lista2) {
                                aux2++;
                            }
                            lista2.remove(k);
                        }
                    }
                }
            }
        }
        casos.setText("" + aux2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        simulaciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        realizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        casos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        probabilidad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        simular = new javax.swing.JCheckBox();
        generar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Nº de simulaciones");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 130, 16);
        getContentPane().add(simulaciones);
        simulaciones.setBounds(150, 40, 160, 22);

        jLabel2.setText("Numeros Seleccionados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 150, 16);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla1);
        if (tabla1.getColumnModel().getColumnCount() > 0) {
            tabla1.getColumnModel().getColumn(0).setResizable(false);
            tabla1.getColumnModel().getColumn(1).setResizable(false);
            tabla1.getColumnModel().getColumn(2).setResizable(false);
            tabla1.getColumnModel().getColumn(3).setResizable(false);
            tabla1.getColumnModel().getColumn(4).setResizable(false);
            tabla1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 160, 220, 30);

        jLabel3.setText("Numeros Obtenidos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 130, 140, 16);

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo);
        nuevo.setBounds(130, 230, 67, 25);

        realizar.setText("Realizar");
        realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarActionPerformed(evt);
            }
        });
        getContentPane().add(realizar);
        realizar.setBounds(320, 230, 79, 25);

        jLabel4.setText("Frecuencia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 90, 16);

        jLabel5.setText("Casos favorables");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 310, 100, 16);

        casos.setEditable(false);
        getContentPane().add(casos);
        casos.setBounds(140, 310, 90, 22);

        jLabel6.setText("Probabilidad (%)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(261, 310, 110, 16);

        probabilidad.setEditable(false);
        getContentPane().add(probabilidad);
        probabilidad.setBounds(380, 310, 110, 22);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla2);
        if (tabla2.getColumnModel().getColumnCount() > 0) {
            tabla2.getColumnModel().getColumn(0).setResizable(false);
            tabla2.getColumnModel().getColumn(1).setResizable(false);
            tabla2.getColumnModel().getColumn(2).setResizable(false);
            tabla2.getColumnModel().getColumn(3).setResizable(false);
            tabla2.getColumnModel().getColumn(4).setResizable(false);
            tabla2.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(290, 160, 220, 30);

        simular.setText("Simular");
        getContentPane().add(simular);
        simular.setBounds(80, 90, 73, 25);

        generar.setText("Generar");
        getContentPane().add(generar);
        generar.setBounds(220, 90, 75, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarActionPerformed
        generar();
    }//GEN-LAST:event_realizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casos;
    private javax.swing.JCheckBox generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextField probabilidad;
    private javax.swing.JButton realizar;
    private javax.swing.JTextField simulaciones;
    private javax.swing.JCheckBox simular;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
